backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Kooperativet"
    name: "cooperative"
    files:
      - label: "Föräldrainsats"
        name: "parent_engagement"
        file: "src/_data/parent_engagement.yaml"
        fields:
          - { label: "Beskrivning", name: "description", widget: "string" }
      - label: "Verksamheten"
        name: "workgroups"
        file: "src/_data/workgroups.yaml"
        editor:
          preview: false
        fields:
          - label: "Verksamheten"
            name: "workgroups"
            widget: list
            fields:
              - { label: "Arbetsgrupp", name: "name", widget: "string" }
              - { label: "Beskrivning", name: "desc", widget: "markdown" }
  - label: "Personal"
    name: "personell"
    files:
      - label: "Pedagoger"
        name: "educators"
        file: "src/_data/educators.yaml"
        editor:
          preview: false
        fields:
          - label: "Pedagoger"
            name: "educators"
            widget: list
            fields:
              - { label: "Namn", name: "name", widget: "string" }
              - { label: "Profil", name: "avatar", widget: "image", required: false}
              - { label: "Beskrivning", name: "desc", widget: "string" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Sektioner på startsidan"
        name: "frontpage_sections"
        file: "src/_data/sections.yaml"
        fields:
          - label: Section items
            name: sections
            widget: list
            collapsed: true
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Id, name: id, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Beskrivning, name: desc, widget: markdown }
              - { label: Bild, name: image, widget: image, required: false }
      # Our pages e.g. About
      - name: "home"
        label: "Home"
        file: "src/_data/home.yaml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - label: "Navigation"
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Order", name: "order", widget: "number", default: 0 }
          - {
              label: "Beskrivning",
              name: "headerDescription",
              widget: "markdown",
            }
          - label: Varför Sagolunden
            name: whyPickUs
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Beskrivning, name: desc, widget: markdown }
      - name: "education"
        label: "Utbildning"
        file: "src/_data/education.yaml"
        fields:
          - { label: "Beskrivning", name: "description", widget: markdown }
      - name: "contact"
        label: "Contact"
        file: "src/_data/contact.yaml"
        fields:
          - { label: "Description", name: "description", widget: "string"}
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Postkod", name: "postalCode", widget: "string" }
          - { label: "Ort", name: "county", widget: "string"}
          - { label: "Tel", name: "telephone", widget: "string"}
          - label: Social Media
            name: socialMedia
            widget: list
            allow_add: true
            fields:
              - { label: Name, name: name, widget: string}
              - { label: Url, name: url, widget: string}
              - { label: Icon, name: icon, widget: image}
