backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Kooperativet"
    name: "cooperative"
    files:
      - label: "Arbetsgrupper"
        name: "workgroups"
        file: "src/_data/workgroups.yaml"
        editor:
          preview: false
        fields:
          - label: "Arbetsgrupper"
            name: "workgroups"
            widget: list
            fields:
              - { label: "Arbetsgrupp", name: "name", widget: "string" }
              - { label: "Beskrivning", name: "desc", widget: "string" }
              - label: "Medlemmar"
                name: "members"
                widget: list
                fields:
                  - { label: "Namn", name: "name", widget: "string" }
                  - {
                      label: "Ytterliggare ansvar",
                      name: "additional_role",
                      widget: "string",
                    }
  - label: "Personal"
    name: "personell"
    files:
      - label: "Pedagoger"
        name: "educators"
        file: "src/_data/educators.yaml"
        editor:
          preview: false
        fields:
          - label: "Pedagoger"
            name: "educators"
            widget: list
            fields:
              - { label: "Namn", name: "name", widget: "string" }
              - { label: "Beskrivning", name: "desc", widget: "string" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Sektioner på startsidan"
        name: "frontpage_sections"
        file: "src/_data/sections.yaml"
        fields:
          - label: Section items
            name: sections
            widget: list
            collapsed: true
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Beskrivning, name: desc, widget: markdown }
      # Our pages e.g. About
      - name: "home"
        label: "Home"
        file: "src/_data/home.yaml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Order", name: "order", widget: "number", default: 0 }
          - {
              label: "Beskrivning",
              name: "headerDescription",
              widget: "markdown",
            }
          - label: Varför Sagolunden
            name: whyPickUs
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Beskrivning, name: desc, widget: markdown }
